#!/usr/bin/env python3
"""
qr-decode.py — decodes a GLYPHBOX Aztec card set back to a .gbcart file.

Supports three modes:
  • Static image — reads a PNG/JPG scan of a card rear
  • PDF          — renders a card PDF rear page and decodes from it
  • Webcam       — opens the system camera and scans live frames

Multi-card tiered format (generated by qr-encode.py):
  Each physical card has ONE Aztec code on its rear.
  Payload per code:
    byte[0]  — chunk index   (0 … N-1)
    byte[1]  — total cards   (N — number of cards in the set)
    byte[2]  — flags         (0x01 = zlib-compressed whole cart)
    byte[3+] — chunk data

  Card sets: 1, 2, 4, 8, or 16 cards (smallest power of 2 that fits).
  Codes are self-identifying — scan them in any order, one at a time.

  halves dict layout:
    halves[idx]  = (flags, chunk_data)  for each captured card index
    halves[-1]   = total                sentinel: total cards in set

Usage:
    python tools/qr-decode.py scan.png     -o recovered.gbcart
    python tools/qr-decode.py card.pdf     -o recovered.gbcart
    python tools/qr-decode.py --webcam     -o recovered.gbcart
    python tools/qr-decode.py --webcam --device 1 -o recovered.gbcart
"""

import argparse
import os
import sys
from pathlib import Path
import struct

def _card_label(idx: int, total: int) -> str:
    """Return a human-readable card label, e.g. '3/8'."""
    return f"{idx + 1}/{total}"

# Minimum render DPI for reliable Aztec decoding (used for PDF inputs).
# Dense Aztec codes (> ~400 bytes/chunk) need ≥7 px/module to decode; at 72 dpi
# base that requires 12×.  Lower values work for sparse carts (bouncer etc.)
# but fail silently for denser ones such as the tennis or runner carts.
_PDF_ZOOM = 12  # 12× = ~864 DPI equivalent at 72 DPI base


# ── Dependency helpers ────────────────────────────────────────────────────────

def _require(pkg_import: str, pip_name: str):
    """Import a module, exiting with a pip-install hint if missing."""
    import importlib
    try:
        return importlib.import_module(pkg_import)
    except ImportError:
        sys.exit(f"Missing dependency: pip install {pip_name}")


# ── Core Aztec scanner (uses zxing-cpp) ──────────────────────────────────────

def _aztec_hints(zxingcpp):
    """
    Build read_barcodes keyword arguments that restrict the scan to Aztec
    format and maximise the search effort for distorted/wide-angle frames.

    Restricting to Aztec makes each pass 5–10× faster on Pi ARM CPUs since
    the decoder skips QR, DataMatrix, DataBar, etc.

    try_rotate / try_downscale / try_invert are already True by default in
    zxing-cpp; we set them explicitly so older builds that default them False
    still benefit.  Note: some builds spell this "try_harder" — we probe the
    API once at startup and cache whichever kwargs are accepted.
    """
    hints: dict = {}

    # Restrict to Aztec format only
    try:
        hints["formats"] = zxingcpp.BarcodeFormat.Aztec
    except AttributeError:
        pass   # very old build without per-format filtering

    # Probe for exhaustive-search parameters — API varies by build version
    import inspect
    try:
        sig = inspect.signature(zxingcpp.read_barcodes)
        params = sig.parameters
        for key in ("try_rotate", "try_downscale", "try_invert"):
            if key in params:
                hints[key] = True
    except (TypeError, ValueError):
        pass   # can't introspect — skip

    return hints


def _play_ding() -> None:
    """
    Play a short two-tone ascending chime when a card is successfully scanned.
    Runs in a daemon thread so it never blocks the scan loop.
    Pure stdlib — no extra dependencies (wave + struct + math + subprocess).
    Falls back silently if aplay is unavailable (Mac / no ALSA).
    """
    import io, math, struct, subprocess, threading, wave

    def _build_wav(freqs_dur: list, rate: int = 44100) -> bytes:
        buf = io.BytesIO()
        with wave.open(buf, 'wb') as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(rate)
            samples = []
            for freq, dur, vol in freqs_dur:
                n = int(rate * dur)
                for i in range(n):
                    t        = i / rate
                    envelope = math.exp(-t * 10)          # fast exponential decay
                    s        = vol * envelope * math.sin(2 * math.pi * freq * t)
                    samples.append(struct.pack('<h', int(32767 * s)))
            w.writeframes(b''.join(samples))
        return buf.getvalue()

    def _worker():
        try:
            # Two ascending tones: 660 Hz (80 ms) then 880 Hz (160 ms)
            wav = _build_wav([(660, 0.08, 0.55), (880, 0.16, 0.70)])
            import sys as _sys, tempfile as _tmp, os as _os
            if _sys.platform == "darwin":
                # macOS: write to a temp file and play with afplay
                with _tmp.NamedTemporaryFile(suffix=".wav", delete=False) as f:
                    f.write(wav)
                    tmp_path = f.name
                try:
                    subprocess.run(
                        ['afplay', tmp_path],
                        capture_output=True, timeout=2
                    )
                finally:
                    _os.unlink(tmp_path)
            else:
                # Linux/Pi: pipe directly to aplay via stdin
                subprocess.run(
                    ['aplay', '-q', '-'],
                    input=wav, capture_output=True, timeout=2
                )
        except Exception:
            pass   # audio not available — silently skip

    threading.Thread(target=_worker, daemon=True).start()


def _is_complete(halves: dict) -> bool:
    """Return True when all expected chunks have been captured."""
    total = halves.get(-1, 0)
    if total == 0:
        return False
    return all(i in halves for i in range(total))


def _scan_for_halves(pil_img, camera_mode: bool = False) -> dict:
    """
    Scan a PIL Image for one or more Aztec codes in the multi-card format.
    Returns a dict:
        chunk-index (0 … N-1)  →  (flags_byte, chunk_data_bytes)
        -1                     →  total   (number of cards in the set)

    Payload format per code (generated by qr-encode.py):
        byte[0]  — chunk index  (0 … N-1)
        byte[1]  — total cards  (N)
        byte[2]  — flags        (0x01 = zlib-compressed)
        byte[3+] — chunk data

    Binarisation strategy:
      Pass 1 – zxing-cpp's built-in LocalAverage binariser.
               Works well for real-world webcam frames with uneven lighting.
      Pass 2 – Hard threshold to pure B&W (L < 128 → 0, else 255).
               PDF-rendered and screen-displayed codes are anti-aliased at
               module edges; the fringe grey pixels confuse LocalAverage.
               A global threshold restores the clean binary signal.

    camera_mode=True adds passes 3–4, suited to live camera frames:
      Pass 3 – CLAHE (local contrast normalisation) — evens out uneven
               lighting across the frame.
      Pass 4 – Adaptive threshold on CLAHE image — locally binarises each
               8×8 tile independently; handles gradients and glare.
    """
    zxingcpp = _require("zxingcpp", "zxing-cpp")
    halves: dict = {}
    hints = _aztec_hints(zxingcpp)   # Aztec-only + try_harder

    # Valid tier sizes produced by qr-encode.py (powers of 2, ≤ 16 cards)
    _VALID_TOTALS = frozenset({1, 2, 4, 8, 16})

    def _extract(pil) -> None:
        for r in zxingcpp.read_barcodes(pil, **hints):
            if not r.valid or len(r.bytes) < 4:
                continue
            # Only accept Aztec codes — other formats (DataBar, QR, etc.)
            # can produce false positives whose raw bytes corrupt the
            # [index, total, flags, data] payload parse.
            if "aztec" not in str(r.format).lower():
                continue
            idx   = r.bytes[0]   # chunk index (0 … N-1)
            total = r.bytes[1]   # total cards in set
            flags = r.bytes[2]   # 0x01 = zlib compressed
            data  = r.bytes[3:]
            # Reject impossible totals (must be a power-of-2 tier value)
            # and out-of-range indices.
            if total not in _VALID_TOTALS or idx >= total:
                continue
            # Record total as sentinel (first Aztec code wins)
            if -1 not in halves:
                halves[-1] = total
            if idx not in halves:
                halves[idx] = (flags, data)
                print(f"  Found Card {_card_label(idx, total)}: "
                      f"{len(data):,} bytes  (format={r.format})")

    # Pass 1 — native binariser
    _extract(pil_img)
    if _is_complete(halves):
        return halves

    # Pass 2 — hard-threshold fallback (fixes anti-aliased PDF/screen renders)
    bw = pil_img.convert("L").point(lambda v: 0 if v < 128 else 255, "1").convert("RGB")
    _extract(bw)
    if _is_complete(halves) or not camera_mode:
        return halves

    # Passes 3–12: camera-specific preprocessing ──────────────────────────
    try:
        import cv2
        import numpy as np
        from PIL import Image as _Image

        frame = np.array(pil_img.convert("RGB"))
        gray  = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
        H, W  = gray.shape

        clahe    = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        enhanced = clahe.apply(gray)

        def _pil(g):
            return _Image.fromarray(cv2.cvtColor(g, cv2.COLOR_GRAY2RGB))

        # Pass 3 — CLAHE full frame
        _extract(_pil(enhanced))
        if _is_complete(halves):
            return halves

        # Pass 4 — adaptive threshold on CLAHE full frame
        adaptive = cv2.adaptiveThreshold(
            enhanced, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5
        )
        _extract(_pil(adaptive))
        if _is_complete(halves):
            return halves

    except Exception:
        pass   # cv2/numpy unavailable or error — fall back to what we have

    return halves


# ── Static image mode ─────────────────────────────────────────────────────────

def decode_from_image(image_path: str, output_path: str) -> None:
    Image = _require("PIL.Image", "pillow")

    print(f"Scanning: {image_path}")
    img = Image.open(image_path).convert("RGB")
    halves = _scan_for_halves(img)
    _check_and_write(halves, output_path)


# ── PDF mode ──────────────────────────────────────────────────────────────────

def decode_from_pdf(pdf_path: str, output_path: str, page_index: int = 1) -> None:
    """
    Render the specified page of a PDF (default: page 2 = rear) at high resolution
    and decode the Aztec codes from it.
    """
    fitz = _require("fitz", "pymupdf")
    Image = _require("PIL.Image", "pillow")

    print(f"Rendering PDF: {pdf_path}  (page {page_index + 1})")
    doc = fitz.open(pdf_path)
    if page_index >= len(doc):
        sys.exit(f"PDF has only {len(doc)} page(s); requested page {page_index + 1}.")
    mat = fitz.Matrix(_PDF_ZOOM, _PDF_ZOOM)
    pix = doc[page_index].get_pixmap(matrix=mat)
    doc.close()

    img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
    print(f"  Rendered at {pix.width}×{pix.height}px ({_PDF_ZOOM}× zoom)")
    halves = _scan_for_halves(img)
    _check_and_write(halves, output_path)


# ── Webcam mode ───────────────────────────────────────────────────────────────

def _undistort_frame(pil_img, k1: float = None, k2: float = None):
    """
    Apply barrel distortion correction for the Arducam / IMX708-wide lens.

    The imx708_wide is a ~120° FOV fisheye-class lens that produces heavy
    barrel distortion (edges bow outward).  Aztec codes rely on a regular
    square grid; even moderate distortion prevents zxing-cpp from locating
    the finder-pattern corners.

    Default coefficients are tuned for the IMX708 wide (Camera Module 3 Wide).
    Override via --distort-k1 / --distort-k2 CLI flags, or place exact values
    from checkerboard calibration in ~/.glyphbox/camera_cal.npz.

    Tuning guide (add to ~/.glyphbox/scanner_flags):
        --distort-k1 -0.42   # stronger correction  (more distorted lens)
        --distort-k1 -0.30   # weaker  correction  (less distorted lens)
    """
    import cv2
    import numpy as np
    from pathlib import Path
    from PIL import Image as _Image

    frame = np.array(pil_img.convert("RGB"))
    h, w  = frame.shape[:2]

    # Load saved calibration if available — highest priority
    cal_path = Path.home() / ".glyphbox" / "camera_cal.npz"
    if cal_path.exists():
        cal  = np.load(str(cal_path))
        K, D = cal["K"], cal["D"]
    else:
        # IMX708 wide: ~120° diagonal FOV → focal length ≈ w * 0.77
        # k1 ≈ -0.42 for the factory imx708_wide lens.
        # k2 partially corrects the k1 over-correction at frame edges.
        _k1 = k1 if k1 is not None else -0.42
        _k2 = k2 if k2 is not None else  0.12
        f = w * 0.77
        K = np.array([[f, 0, w / 2],
                      [0, f, h / 2],
                      [0, 0,     1]], dtype=np.float64)
        D = np.array([_k1, _k2, 0.0, 0.0, 0.0])

    return _Image.fromarray(cv2.undistort(frame, K, D))


def _open_picamera2() -> tuple:
    """
    Open the Arducam/CSI camera via picamera2.  Raises ImportError if
    picamera2 is not installed, or RuntimeError on configuration failure.

    Returns (capture_fn, close_fn).
    """
    import time as _time
    from picamera2 import Picamera2
    Image = _require("PIL.Image", "pillow")

    cam = Picamera2()
    # Video configuration streams from a ring buffer at full sensor fps.
    # Still configuration captures single-shot stills — far slower for live
    # preview.  1920×1080 gives more pixels-per-module for dense Aztec codes,
    # which is critical for tennis/pac-level carts on a wide-angle lens.
    cfg = cam.create_video_configuration(
        main={"size": (1920, 1080), "format": "RGB888"},
        buffer_count=4,
    )
    cam.configure(cfg)

    cam.start()
    _time.sleep(0.5)   # video mode converges AE/AWB faster than still mode

    # Enable continuous autofocus (AfMode=2) on cameras that support it
    # (e.g. Arducam 75D AF, Pi Camera Module 3 AF).  Without this the IMX708 AF
    # stays at its default focus distance and the code appears blurry even
    # though rpicam-hello looks sharp (it enables AF automatically).
    # Non-AF cameras (fixed-focus) silently ignore these controls.
    try:
        cam.set_controls({"AfMode": 2, "AfSpeed": 1})
        _time.sleep(0.5)   # allow AF to converge before first capture
    except Exception:
        pass

    print("Camera: Arducam / picamera2  (1920×1080 video)")

    def capture():
        import numpy as np
        return Image.fromarray(cam.capture_array())

    def close():
        cam.stop()
        cam.close()

    return capture, close


def _open_opencv_camera(device: int) -> tuple:
    """
    Open a webcam via OpenCV VideoCapture (desktop fallback).

    Returns (capture_fn, close_fn).
    """
    cv2   = _require("cv2", "opencv-python")
    Image = _require("PIL.Image", "pillow")

    cap = cv2.VideoCapture(device)
    if not cap.isOpened():
        sys.exit(f"Cannot open webcam (device {device})")
    cap.set(cv2.CAP_PROP_FRAME_WIDTH,  1920)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
    actual_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    actual_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"Camera: OpenCV device {device}  ({actual_w}×{actual_h})")

    def capture():
        ret, frame = cap.read()
        if not ret:
            return None
        return Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

    def close():
        cap.release()

    return capture, close


def _open_webcam_camera(device: int, force_pi: bool = False) -> tuple:
    """
    Open the best available camera.

    force_pi=True  — use picamera2 directly; exit with a clear error if it is
                     not available.  Passed when --pi-camera is set (i.e. the
                     binary was built with PLATFORM=PI_HDMI).
    force_pi=False — try picamera2 first, fall back to OpenCV VideoCapture.

    Returns (capture_fn, close_fn).
    """
    if force_pi:
        try:
            return _open_picamera2()
        except ImportError:
            sys.exit(
                "picamera2 is not installed.\n"
                "On Raspberry Pi: sudo apt install python3-picamera2\n"
                "Or: pip install picamera2"
            )

    # Auto-detect: try picamera2 first, fall back to OpenCV.
    try:
        return _open_picamera2()
    except ImportError:
        return _open_opencv_camera(device)


def _send_cam_frame(pil, halves: dict, cam_fd: int) -> bool:
    """
    Downscale pil to 128×128 grayscale, draw a single-code target box and
    card-progress indicators, then write a GCAM-framed frame to cam_fd
    (non-blocking).

    Multi-card scanning UI:
      • Large centred rectangle — align the REAR of the current card here.
      • Row of small squares at the bottom — one per card in the set.
        Filled square = captured, outline = still needed.
      • Progress text above the target box: "CARD 2/4 SCANNED" etc.

    Overlay elements use only pure white (255) and black (0) to match the
    GLYPHBOX 1-bit aesthetic.  The camera feed is grayscale so the user can
    see the card clearly for alignment.

    Returns False if the pipe is permanently broken (caller should close fd).
    """
    try:
        import cv2
        import numpy as np

        W, H = 128, 128

        # Downscale full-res frame → 128×128 then convert to grayscale.
        frame_small = cv2.resize(
            np.array(pil), (W, H), interpolation=cv2.INTER_NEAREST
        )
        gray = cv2.cvtColor(frame_small, cv2.COLOR_RGB2GRAY)

        # ── Target alignment rectangle (single-code, centred) ─────────────
        zw = int(W * 0.72)    # 92 px wide
        zh = int(H * 0.72)    # 92 px tall
        zx = (W - zw) // 2   # 18 px from left
        zy = int(H * 0.10)   # 13 px from top

        cv2.rectangle(gray, (zx, zy), (zx + zw - 1, zy + zh - 1), 255, 1)

        # Corner ticks inside the target box (L-shaped, 6 px legs)
        tk = 6
        for cx, cy in [(zx, zy), (zx + zw - 1, zy),
                       (zx, zy + zh - 1), (zx + zw - 1, zy + zh - 1)]:
            dx = 1 if cx == zx else -1
            dy = 1 if cy == zy else -1
            cv2.line(gray, (cx, cy), (cx + dx * tk, cy), 255, 1)
            cv2.line(gray, (cx, cy), (cx, cy + dy * tk), 255, 1)

        # ── Text overlay via PIL pixel bitmap font ────────────────────────
        from PIL import Image as _PILImage, ImageDraw as _Draw, ImageFont as _Font
        _pil_gray = _PILImage.fromarray(gray)
        _dr       = _Draw.Draw(_pil_gray)
        # Cache the default font so it is loaded only once across all frames.
        if not hasattr(_send_cam_frame, "_fnt"):
            _send_cam_frame._fnt = _Font.load_default()
        _fnt = _send_cam_frame._fnt

        # ── "GLYPHBOX" title ──────────────────────────────────────────────
        _dr.text((26, 1), "GLYPHBOX", fill=255, font=_fnt)

        # ── Progress row — one square per card in the set ─────────────────
        total    = halves.get(-1, 0)
        captured = sum(1 for k in halves if isinstance(k, int) and k >= 0)

        if total > 0:
            prog_text = f"{captured}/{total} SCANNED"
            _dr.text((4, zy + zh + 2), prog_text, fill=255, font=_fnt)
        else:
            _dr.text((4, H - 10), "FRAME REAR OF CARD", fill=255, font=_fnt)

        # Convert PIL text back to numpy, then draw progress squares on top.
        # Squares use cv2 so they stay crisp binary pixels (no AA fringe).
        gray = np.array(_pil_gray)

        if total > 0:
            sq    = 7                              # square side (px)
            gap   = 3                              # gap between squares
            row_w = total * sq + (total - 1) * gap
            rx    = (W - row_w) // 2
            ry    = H - sq - 3
            for i in range(total):
                bx = rx + i * (sq + gap)
                if i in halves:
                    cv2.rectangle(gray, (bx, ry), (bx + sq, ry + sq), 255, -1)
                else:
                    cv2.rectangle(gray, (bx, ry), (bx + sq, ry + sq), 255,  1)

        # Write GCAM header (magic + uint16 W + uint16 H) then pixel data
        header = b'GCAM' + struct.pack('<HH', W, H)
        os.write(cam_fd, header + gray.tobytes())
        return True

    except BlockingIOError:
        return True   # reader is behind — skip this frame, scanning continues
    except OSError:
        return False  # broken pipe or write error — caller should close fd
    except Exception:
        return True   # cv2/numpy error — non-fatal, keep scanning


def decode_from_webcam(output_path: str, device: int = 0,
                       headless: bool = False,
                       cam_fifo: str = "",
                       force_pi: bool = False,
                       no_undistort: bool = False,
                       save_frame: str = "",
                       distort_k1: float = None,
                       distort_k2: float = None) -> None:
    """
    Scan live camera frames for all Aztec chunks in a multi-card set, then
    assemble the cartridge.  The number of required cards is determined
    automatically from the first code decoded (its total_byte field).

    headless=True     — skips the standalone OpenCV preview window (used when
                        launched as a subprocess by the glyphbox runtime).
    cam_fifo          — when non-empty, stream 128×128 grayscale frames with
                        alignment overlays to this FIFO path so the runtime
                        can display a live camera feed inside its SDL2 window.
    force_pi=True     — use picamera2 directly; set when launched via
                        --pi-camera (the Pi build flag).
    no_undistort      — barrel-distortion correction is OFF by default.
                        Pass --undistort to enable it (only needed for
                        wide-angle / fisheye lenses such as the imx708_wide).
    """
    capture, close_camera = _open_webcam_camera(device, force_pi=force_pi)

    # --save-frame: grab one frame, write it to disk, and exit.
    # Use this to inspect camera image quality before running a full scan.
    if save_frame:
        import time
        print("Hold your code in front of the camera now.")
        for i in (5, 4, 3, 2, 1):
            print(f"  Capturing in {i}…")
            time.sleep(1)
        pil = capture()
        close_camera()
        if pil is None:
            sys.exit("Camera read error — could not capture a frame.")
        pil.save(save_frame)
        w, h = pil.size
        print(f"Frame saved: {save_frame}  ({w}×{h})")
        print("Copy to your Mac with:  scp pi@raspberrypi.local:" + save_frame + " ~/Desktop/frame.jpg")
        return

    # If no display is available (e.g. SSH session on Pi) automatically fall
    # back to headless mode rather than crashing when cv2.imshow is called.
    if not headless and not no_undistort:   # only probe if we'd actually show
        try:
            import cv2
            # A zero-wait on a tiny image is enough to trigger the Qt/XCB
            # platform plugin load; catch the abort before it kills us.
            cv2.waitKey(1)
        except Exception:
            pass
    if not headless:
        try:
            import cv2
            import os as _os
            if not _os.environ.get("DISPLAY") and not _os.environ.get("WAYLAND_DISPLAY"):
                print("No display detected — switching to headless mode.", file=sys.stderr)
                headless = True
        except ImportError:
            headless = True

    # Open the camera FIFO for non-blocking writes (subprocess/headless mode).
    # main.c opens the read end before forking, so the reader is always present.
    cam_fd = -1
    if cam_fifo:
        try:
            cam_fd = os.open(cam_fifo, os.O_WRONLY | os.O_NONBLOCK)
        except OSError as e:
            print(f"GLYPHBOX: cam-fifo open failed: {e}", file=sys.stderr)

    halves: dict = {}
    _attempt = 0   # decode attempts counter (for periodic feedback)
    print("═══════════════════════════════════════════")
    print("  GLYPHBOX Card Scanner — webcam mode")
    print("  Point camera at the REAR of each card.")
    print("  Codes are self-identifying — any order.")
    if not headless:
        print("  Press  Q  to abort.")
    print("═══════════════════════════════════════════\n")

    # ── Threaded Aztec scanning ────────────────────────────────────────────
    # zxing-cpp can take 100-400 ms per frame on a Pi.  Running it on the
    # main thread would cap the preview at 2-10 fps.  Instead, a background
    # daemon thread owns the decode; the main loop captures + streams at full
    # camera fps and merges any newly found codes each iteration.
    import threading

    _scan_pending:  dict = {}   # results written by scan thread
    _scan_lock      = threading.Lock()
    _scan_thread: list = [None] # mutable cell so the closure can reassign

    def _scan_worker(snap):
        # Apply lens undistortion here, inside the background thread, so the
        # main capture loop never blocks on the expensive cv2.undistort call.
        if force_pi and not no_undistort:
            snap = _undistort_frame(snap, k1=distort_k1, k2=distort_k2)
        # Downscale to 960×540 before the 4-pass pipeline.
        # CLAHE and adaptive threshold cost scales with pixel count — this
        # gives a 4× reduction in work with negligible impact on Aztec
        # decode accuracy (still ~300 px per code side at typical distance).
        if snap.width > 960:
            snap = snap.resize((960, 540))
        result = _scan_for_halves(snap, camera_mode=True)
        with _scan_lock:
            _scan_pending.update(result)

    def _maybe_launch_scan(pil):
        """Start a new scan thread if the previous one has finished.
        Returns True if a new thread was launched."""
        t = _scan_thread[0]
        if t is None or not t.is_alive():
            snap = pil.copy()   # copy so the main loop can reuse pil
            t = threading.Thread(target=_scan_worker, args=(snap,), daemon=True)
            t.start()
            _scan_thread[0] = t
            return True
        return False

    def _collect_scan_results():
        """Drain any codes the scan thread found; return True if new codes arrived."""
        with _scan_lock:
            if not _scan_pending:
                return False
            new = dict(_scan_pending)
            _scan_pending.clear()
        found_new = False
        # Merge sentinel (-1 = total) first so label printing is correct
        if -1 in new and -1 not in halves:
            halves[-1] = new.pop(-1)
        else:
            new.pop(-1, None)
        total = halves.get(-1, 0)
        for idx, (flags, payload) in new.items():
            if isinstance(idx, int) and idx >= 0 and idx not in halves:
                halves[idx] = (flags, payload)
                lbl = _card_label(idx, total) if total else str(idx + 1)
                print(f"  ✓ Card {lbl} captured ({len(payload):,} bytes)")
                _play_ding()
                found_new = True
        return found_new
    # ──────────────────────────────────────────────────────────────────────

    try:
        while True:
            pil = capture()
            if pil is None:
                print("Camera read error", file=sys.stderr)
                break

            # Merge any codes the background thread decoded
            _collect_scan_results()

            # Launch a new scan if the worker is idle (non-blocking)
            if not _is_complete(halves):
                launched = _maybe_launch_scan(pil)
                if launched:
                    _attempt += 1
                    if _attempt % 10 == 1:   # print every 10th attempt
                        print(f"  Scanning… (attempt {_attempt})", flush=True)

            # Stream frame to glyphbox runtime (no-op if cam_fd == -1)
            if cam_fd >= 0:
                if not _send_cam_frame(pil, halves, cam_fd):
                    os.close(cam_fd)
                    cam_fd = -1

            if _is_complete(halves):
                total = halves.get(-1, 0)
                print(f"\nAll {total} card{'s' if total != 1 else ''} captured "
                      f"— assembling cartridge…")
                break

            if not headless:
                # Show preview window with status overlay (desktop mode only).
                # On Pi, downscale to 960×540 before imshow — rendering a
                # full 1920×1080 frame via OpenCV/X11 is slow and adds lag.
                import cv2
                import numpy as np
                total    = halves.get(-1, 0)
                captured = sum(1 for k in halves if isinstance(k, int) and k >= 0)
                if total:
                    status = f"Cards scanned: {captured} / {total}"
                else:
                    status = "Waiting for first card…"
                frame = cv2.cvtColor(np.array(pil), cv2.COLOR_RGB2BGR)
                if force_pi:
                    frame = cv2.resize(frame, (960, 540), interpolation=cv2.INTER_NEAREST)
                cv2.putText(frame, status, (10, 38),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 220, 0), 2,
                            cv2.LINE_AA)
                cv2.imshow("GLYPHBOX Scanner  [Q = quit]", frame)
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    print("Scan cancelled.", file=sys.stderr)
                    sys.exit(1)
    finally:
        close_camera()
        if cam_fd >= 0:
            try:
                os.close(cam_fd)
            except OSError:
                pass
        if not headless:
            try:
                import cv2
                cv2.destroyAllWindows()
            except Exception:
                pass

    _check_and_write(halves, output_path)


# ── Reassembly ────────────────────────────────────────────────────────────────

def _check_and_write(halves: dict, output_path: str) -> None:
    # Determine total from sentinel; fall back to highest seen index + 1
    if -1 in halves:
        total = halves[-1]
    elif halves:
        total = max(k for k in halves if isinstance(k, int) and k >= 0) + 1
    else:
        total = 0

    if total == 0:
        sys.exit(
            "No GLYPHBOX Aztec codes found.\n"
            "Ensure the image is a clear scan of the card rear.\n"
            "Tip: improve lighting, reduce glare, or increase image resolution."
        )

    found   = [str(i + 1) for i in range(total) if i     in halves]
    missing = [str(i + 1) for i in range(total) if i not in halves]

    if not found:
        sys.exit(
            "No GLYPHBOX Aztec codes found.\n"
            "Ensure the image is a clear scan of the card rear.\n"
            "Tip: improve lighting, reduce glare, or increase image resolution."
        )
    if missing:
        sys.exit(
            f"Found card(s) {', '.join(found)} of {total} — "
            f"missing card(s) {', '.join(missing)}.\n"
            f"All {total} cards are required to reassemble the cartridge."
        )

    flags    = halves[0][0]   # flags byte — all codes share the same value
    combined = b"".join(halves[i][1] for i in range(total))

    if flags & 0x01:
        import zlib
        try:
            raw_sz   = sum(len(halves[i][1]) for i in range(total))
            combined = zlib.decompress(combined)
            print(f"Decompressed: {raw_sz:,} → {len(combined):,} bytes")
        except zlib.error as e:
            sys.exit(f"Decompression failed: {e}\n"
                     "The cart data may be corrupt or was encoded without compression.")

    Path(output_path).write_bytes(combined)
    print(f"Written: {output_path}  ({len(combined):,} bytes)")

    if combined[:4] == b"GBC1":
        print("Magic GBC1 confirmed ✓")
    else:
        print("Warning: magic bytes don't match 'GBC1' — data may be corrupt.")


# ── Entry point ───────────────────────────────────────────────────────────────

def _load_scanner_flags() -> list:
    """
    Load extra CLI flags from ~/.glyphbox/scanner_flags (one flag per line).
    These are injected before sys.argv so explicit command-line args still
    take precedence.  Blank lines and lines starting with # are ignored.

    Example ~/.glyphbox/scanner_flags contents:
        # Enable lens undistortion for wide-angle cameras (e.g. imx708_wide)
        --undistort

    Supported flags:
        --undistort         Enable barrel-distortion correction (wide-angle only)
        --save-frame PATH   Capture one frame, save to PATH, and exit
    """
    from pathlib import Path
    flags_file = Path.home() / ".glyphbox" / "scanner_flags"
    if not flags_file.exists():
        return []
    lines = flags_file.read_text().splitlines()
    tokens = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        tokens.extend(line.split())
    if tokens:
        print(f"Scanner flags loaded from {flags_file}: {' '.join(tokens)}")
    return tokens


def main():
    parser = argparse.ArgumentParser(
        description="Decode a GLYPHBOX Aztec card (image/PDF/webcam) to a .gbcart file."
    )
    parser.add_argument(
        "input", nargs="?",
        help="PNG/JPG scan or PDF of a card rear (Aztec code must be visible)"
    )
    parser.add_argument("-o", "--output", required=True, help="Output .gbcart file path")
    parser.add_argument("--webcam",    action="store_true",
                        help="Capture from camera (auto-selects picamera2 on Pi, "
                             "OpenCV on desktop)")
    parser.add_argument("--pi-camera", action="store_true",
                        help="Force picamera2 (Arducam/CSI) — passed automatically "
                             "by glyphbox binaries built with PLATFORM=PI_HDMI")
    parser.add_argument("--headless", action="store_true",
                        help="Skip OpenCV preview window (used when launched by glyphbox)")
    parser.add_argument("--device",   type=int, default=0,
                        help="Webcam device index for OpenCV fallback (default: 0)")
    parser.add_argument("--cam-fifo", default="",
                        help="FIFO path for streaming camera frames to the "
                             "glyphbox runtime SDL2 window (set by main.c)")
    parser.add_argument("--undistort", action="store_true",
                        help="Apply barrel-distortion correction. Only needed for "
                             "wide-angle / fisheye lenses (e.g. imx708_wide). "
                             "Standard-FOV cameras (Arducam 75D AF, Pi Camera Module 3) "
                             "do not need this.")
    parser.add_argument("--save-frame", default="", metavar="PATH",
                        help="Capture one frame, save it to PATH (e.g. /tmp/frame.jpg), "
                             "and exit. Use to inspect camera image quality before scanning.")
    parser.add_argument("--distort-k1", type=float, default=None, metavar="K1",
                        help="Barrel distortion k1 coefficient (default: -0.42 for imx708_wide). "
                             "More negative = stronger correction. "
                             "Try -0.35 to -0.50 for the Arducam wide-angle lens. "
                             "Add to ~/.glyphbox/scanner_flags to persist.")
    parser.add_argument("--distort-k2", type=float, default=None, metavar="K2",
                        help="Barrel distortion k2 coefficient (default: 0.12). "
                             "Corrects over-correction at frame edges from k1.")
    parser.add_argument("--pdf-page",     type=int, default=2,
                        help="Which PDF page to decode (1-based, default: 2 = rear)")
    # Inject flags from ~/.glyphbox/scanner_flags before explicit sys.argv
    # so command-line args always win over config-file defaults.
    extra_flags = _load_scanner_flags()
    args = parser.parse_args(extra_flags + sys.argv[1:])

    if args.webcam or args.pi_camera:
        decode_from_webcam(args.output, args.device,
                           headless=args.headless, cam_fifo=args.cam_fifo,
                           force_pi=args.pi_camera,
                           no_undistort=not args.undistort,
                           save_frame=args.save_frame,
                           distort_k1=args.distort_k1,
                           distort_k2=args.distort_k2)
    elif args.input:
        path = args.input.lower()
        if path.endswith(".pdf"):
            decode_from_pdf(args.input, args.output, page_index=args.pdf_page - 1)
        else:
            decode_from_image(args.input, args.output)
    else:
        parser.error("Provide an input file (image or PDF) or use --webcam.")


if __name__ == "__main__":
    main()
